# Generated by Django 5.0.6 on 2024-06-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phn', models.IntegerField(default=None)),
                ('address', models.CharField(max_length=100)),
                ('remember', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cartDetail',
            },
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_or_email', models.CharField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='productDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productDetails_id', models.CharField(max_length=100, unique=True)),
                ('productDetails_name', models.CharField(max_length=100)),
                ('productDetails_brand', models.CharField(max_length=100)),
                ('productDetails_description', models.TextField(default='Lorem, ipsum ', max_length=500)),
                ('productDetails_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productDetails_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('productDetails_category', models.CharField(default=None, max_length=100)),
                ('productDetails_stock', models.IntegerField(default=1)),
                ('is_featured', models.BooleanField(default=False)),
                ('productDetails_image', models.FileField(default=None, max_length=300, null=True, upload_to='products/')),
            ],
            options={
                'db_table': 'productDetail',
            },
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
